### ISSUE TITLE
[Feature request] Focus on redo/undo

### ISSUE THREAD

**Issue by senyaak** [benwbooth/atom-persistent-undo#12]
Current behavior: When I undo the steps I done last time - the cursor do not focus that part. So I cant find what changes were made.(For changes done in current session everything works fine)

Expected behavior: When I do undo - the cursor goes to the line where changes were made.

It would be nice to see the changes I redo/undo.

**Comment by benwbooth** [comment]
Hi,

I'm not maintaining this extension anymore. If you care to submit a pull request, I will accept it. Or if you want to take over the extension or fork it, that's fine too.

**Comment by liquidmetalrob** [comment]
> Current behavior: When I undo the steps I done last time - the cursor do not focus that part. So I cant find what changes were made.(For changes done in current session everything works fine)
> 
> Expected behavior: When I do undo - the cursor goes to the line where changes were made.
> 
> It would be nice to see the changes I redo/undo.

I just fixed this issue in my fork at:
https://github.com/liquidmetalrob/atom-persistent-undo

The last two commits give two ways of doing it: one with less code but retaining all the data about the markers/cursors (including some possibly unnecessary stuff) and the most recent commit uses more code but saves only the strictly necessary data for positioning the cursors to save disk space.

**Comment by benwbooth** [comment]
Hi @liquidmetalrob 

I don't use atom or this plugin any more. Do you want to take over this package? I could transfer this github repository to you and that should allow you to publish the package.

**Comment by liquidmetalrob** [comment]
Hi @benwbooth

Sure, I'd be happy to take over the package. Thanks for the work you did on it.

**Comment by benwbooth** [comment]
It looks like you may need to rename your version of atom-persistent-undo before I can transfer ownership of this one to you. Let me know once you've renamed your version and I will transfer ownership.

**Comment by liquidmetalrob** [comment]
It's renamed now.

**Comment by liquidmetalrob** [comment]
@benwbooth Is it letting you transfer now?

**Comment by benwbooth** [comment]
It's still not letting me transfer because your repository is forked from mine. Can you submit a pull request? Then I will merge in your changes. Then you may need to delete your repository and I will transfer this one to you. Let me know if that sounds reasonable. Thanks!

**Comment by liquidmetalrob** [comment]
I just sent a pull request.

**Comment by benwbooth** [comment]
Thanks! I merged it. Can you please delete your repository and I will transfer this one to you.

**Comment by liquidmetalrob** [comment]
It's deleted now.

**Comment by benwbooth** [comment]
Thanks! I transferred the package to you. According to atom docs that should be all that's needed for you to publish the package. Let me know if you need anything else.

**Comment by liquidmetalrob** [comment]
Thanks very much.
