### ISSUE TITLE
Beware! This package it's making atom not to save files anymore. 

### ISSUE THREAD

**Issue by negru13** [benwbooth/atom-persistent-undo#13]
After installing this, my Atom editor went crazy. Whatever file I was trying to save anywhere on pc was just NOT SAVED! It can make you lose important work. Do not install this crap.

**Comment by benwbooth** [comment]
Hey, thanks for letting me know. I haven't touched this extension in years, since I don't use atom anymore. I posted a warning message in the readme, and I'm trying to figure out how to remove it from the atom repository until someone wants to fix and maintain it.

**Comment by benwbooth** [comment]
OK, the package is unpublished. I'll keep the github repo up with the warning in case anyone wants to fork it and fix it.

**Comment by negru13** [comment]
Hey, sorry man for the harsh message but I was very frustrated when I noticed that my backup files we're not saved.. :( I am convinced that you made some effort in developing this extension and therefore I appreciate that. All the best!

**Comment by benwbooth** [comment]
No problem. I'm glad you let me know so I could stop anyone else from having a bad experience. Thanks!

**Comment by liquidmetalrob** [comment]
Hey Negru, I just fixed the issue and it's working at least on my machine.
I've created a fork at: https://github.com/liquidmetalrob/atom-persistent-undo
Let me know if works for you.

**Comment by liquidmetalrob** [comment]
The fork has now been merged
