### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by ghost** [benwbooth/atom-persistent-undo#2]
Very interesting, but how are you using it? do you have another package for recovering the undo list on next file open?

**Comment by benwbooth** [comment]
This package should be persisting your undo history in your ~/.atom/persistent-undo folder, and should automatically reload it when you open the file again. If it's not working let me know.

**Comment by ghost** [comment]
It works! It didn't at first because I was using "undo" again on the re-opened file, instead of "redo"
